// Error codes for SyftBox client

export enum SyftBoxErrorCode {
  // Authentication errors
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  OTP_REQUIRED = 'OTP_REQUIRED',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',

  // Authorization errors
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Request errors
  INVALID_REQUEST = 'INVALID_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',

  // Network errors
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT = 'TIMEOUT',
  CONNECTION_FAILED = 'CONNECTION_FAILED',

  // Server errors
  SERVER_ERROR = 'SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // WebSocket errors
  WEBSOCKET_CONNECTION_FAILED = 'WEBSOCKET_CONNECTION_FAILED',
  WEBSOCKET_AUTHENTICATION_FAILED = 'WEBSOCKET_AUTHENTICATION_FAILED',
  WEBSOCKET_RECONNECTION_FAILED = 'WEBSOCKET_RECONNECTION_FAILED',

  // Blob storage errors
  BLOB_UPLOAD_FAILED = 'BLOB_UPLOAD_FAILED',
  BLOB_DOWNLOAD_FAILED = 'BLOB_DOWNLOAD_FAILED',
  BLOB_DELETE_FAILED = 'BLOB_DELETE_FAILED',
  BLOB_NOT_FOUND = 'BLOB_NOT_FOUND',
  BLOB_QUOTA_EXCEEDED = 'BLOB_QUOTA_EXCEEDED',

  // RPC errors
  RPC_ERROR = 'RPC_ERROR',
  RPC_TIMEOUT = 'RPC_TIMEOUT',
  RPC_INVALID_RESPONSE = 'RPC_INVALID_RESPONSE',
  RPC_POLL_FAILED = 'RPC_POLL_FAILED',

  // ACL errors
  ACL_ERROR = 'ACL_ERROR',
  ACCESS_DENIED = 'ACCESS_DENIED',

  // Datasite errors
  DATASITE_ERROR = 'DATASITE_ERROR',

  // Configuration errors
  INVALID_CONFIGURATION = 'INVALID_CONFIGURATION',
  MISSING_CONFIGURATION = 'MISSING_CONFIGURATION',

  // General errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
